### ISSUE TITLE
Branch while-loop

### ISSUE THREAD

**Issue by fededev01** [oss-python/exercises-py#1]
Nella branch while-loop, all'interno della cartella together, sono stati aggiunti vari file, che rappresentano i nostri progressi nello sviluppo del programma "maxbwnvalues.py". Attualmente, questo programma non è stato pubblicato, ma appunto le varie versioni dello sviluppo sono presenti nella branch while-loop. La versione più recente è quella "correct.py" presente nella branch while-loop, nella cartella together.

**Comment by YanMark42** [comment]
Sono riuscito a risolvere il massimo nell'array ma non sono riuscito a far si che la lista si chiuda scrivendo "n", devo capire come farlo, per ora l'ho sistemato immettendo 0, se riesco a capire come farlo lo modifico

**Comment by YanMark42** [comment]
Sono riuscito a capire come farlo funzionare facendo immettere "n" per bloccare il ciclo while, posto tutto in "toghether", dagli un'occhiata se ti va

**Comment by fededev01** [comment]
Okay ci do un occhiata

**Comment by fededev01** [comment]
Non ricordo dove stava questo codice. Sarebbe interessante metterlo da qualche parte

**Comment by YanMark42** [comment]
Il codice corretto e funzionante si trova nella branch "while-loop"  cartella together con la versione per far finire l'aggiunta alla lista inserendo 0 oppure la versione che si ferma inserendo "n"
